### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by parthi2929** [dreygur/XDPlugins#9]
Just in case any one wondering, 

1. Zip the respective plugin folder as `.zip`
2. Rename that zip as `.xdx`
3. Double click the `.xdx` file, 
4. Adobe XD opens up, after a little while, asking if you want to install
5. Install and enjoy

Reference:
* [Packaging XD plugin](https://developer.adobe.com/xd/uxp/distribution/packaging-your-plugin/)

**Comment by dreygur** [comment]
Thanks for the contribution :heart:
